
-- Table for therapy/massage detailed content
CREATE TABLE public.terapias_conteudo (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  nome TEXT NOT NULL,
  subtitulo TEXT,
  descricao TEXT,
  beneficios TEXT[] DEFAULT '{}',
  indicacoes TEXT[] DEFAULT '{}',
  contraindicacoes TEXT[] DEFAULT '{}',
  como_funciona TEXT,
  duracao_media TEXT,
  icone TEXT DEFAULT 'Sparkles',
  imagem_capa TEXT,
  galeria_urls TEXT[] DEFAULT '{}',
  video_urls TEXT[] DEFAULT '{}',
  ordem INTEGER DEFAULT 0,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.terapias_conteudo ENABLE ROW LEVEL SECURITY;

-- Public read
CREATE POLICY "Anyone can view active terapias" ON public.terapias_conteudo
  FOR SELECT USING (ativo = true);

-- Admin write
CREATE POLICY "Admins can manage terapias" ON public.terapias_conteudo
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

CREATE TRIGGER update_terapias_conteudo_updated_at
  BEFORE UPDATE ON public.terapias_conteudo
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Seed initial data
INSERT INTO public.terapias_conteudo (slug, nome, subtitulo, descricao, beneficios, indicacoes, contraindicacoes, como_funciona, duracao_media, icone, ordem) VALUES
('liberacao-miofascial', 'Liberação Miofascial', 'Manual e com Ferramentas', 'Técnica que trabalha a fáscia muscular para liberar tensões profundas, restaurar mobilidade e aliviar dores crônicas. Pode ser realizada manualmente ou com ferramentas específicas como ventosas e rolos miofasciais.', ARRAY['Alívio de dores crônicas','Melhora da mobilidade','Redução de tensões musculares','Melhora da postura','Aceleração da recuperação muscular'], ARRAY['Dores musculares crônicas','Restrição de movimento','Fibromialgia','Pós-treino intenso','Tensão cervical e lombar'], ARRAY['Inflamações agudas','Fraturas recentes','Trombose venosa profunda','Infecções cutâneas'], 'A técnica utiliza pressão sustentada e deslizamentos profundos para liberar aderências na fáscia. Com ferramentas, aplica-se pressão direcionada para pontos de gatilho específicos.', '60-90 minutos', 'Sparkles', 1),
('seitai-new-seitai', 'Seitai e New Seitai', 'Quiropraxia Japonesa', 'Método japonês de ajuste corporal que combina técnicas ancestrais com abordagens modernas. O New Seitai integra princípios da quiropraxia ocidental com a filosofia oriental de equilíbrio energético.', ARRAY['Alinhamento postural','Alívio de dores articulares','Equilíbrio do sistema nervoso','Melhora da circulação','Correção de desvios posturais'], ARRAY['Dores na coluna','Desalinhamento postural','Cefaleia tensional','Dores articulares','Rigidez muscular'], ARRAY['Osteoporose severa','Hérnias de disco agudas','Fraturas recentes','Tumores ósseos'], 'Utiliza ajustes suaves e precisos nas articulações e coluna vertebral, combinando palpação diagnóstica com técnicas de correção biomecânica.', '50-70 minutos', 'Hand', 2),
('massagem-relaxante', 'Massagem Relaxante', 'Bem-estar e Descanso', 'Técnica suave e envolvente que promove relaxamento profundo do corpo e mente. Utiliza movimentos rítmicos, deslizamentos longos e pressão moderada para induzir um estado de calma e bem-estar.', ARRAY['Redução do estresse','Melhora do sono','Relaxamento muscular','Redução da ansiedade','Melhora do humor'], ARRAY['Estresse e ansiedade','Insônia','Tensão muscular leve','Cansaço mental','Busca por bem-estar geral'], ARRAY['Febre alta','Infecções cutâneas','Trombose venosa profunda'], 'Combina técnicas de effleurage e petrissage com aromaterapia, em ambiente acolhedor com música relaxante e iluminação suave.', '60-90 minutos', 'Heart', 3),
('massagem-abhyanga', 'Massagem Abhyanga', 'Tradição Ayurvédica', 'Massagem tradicional da medicina Ayurveda indiana, realizada com óleos herbais aquecidos. Trabalha os marmas (pontos vitais) para equilibrar os doshas e promover a desintoxicação do corpo.', ARRAY['Desintoxicação do organismo','Nutrição profunda da pele','Equilíbrio dos doshas','Melhora da circulação linfática','Rejuvenescimento celular'], ARRAY['Desequilíbrio dos doshas','Pele ressecada','Fadiga crônica','Estresse acumulado','Desintoxicação'], ARRAY['Febre','Inflamações cutâneas','Primeiro trimestre de gestação','Indigestão aguda'], 'Óleos herbais aquecidos são aplicados em movimentos rítmicos por todo o corpo, seguindo os meridianos energéticos e pontos marma da tradição ayurvédica.', '75-90 minutos', 'Leaf', 4),
('dry-needling', 'Dry Needling', 'Agulhamento a Seco', 'Técnica que utiliza agulhas filiformes para desativar pontos-gatilho miofasciais, aliviando dor referida e restaurando a função muscular. É uma abordagem baseada em evidências científicas.', ARRAY['Alívio de dor referida','Desativação de pontos-gatilho','Melhora da amplitude de movimento','Redução de espasmos musculares','Aceleração da recuperação'], ARRAY['Pontos-gatilho ativos','Dor miofascial','Cefaleia tensional','Dor cervical e lombar','Lesões esportivas'], ARRAY['Medo de agulhas','Uso de anticoagulantes','Infecções no local','Gestação (áreas específicas)'], 'Agulhas filiformes estéreis são inseridas diretamente nos pontos-gatilho musculares, provocando uma resposta de contração local que libera a tensão muscular.', '30-50 minutos', 'Sparkles', 5),
('kinesio-taping', 'Kinesio Taping', 'Bandagem Neuromuscular', 'Técnica de bandagem elástica que auxilia na recuperação muscular, suporte articular e drenagem linfática. As fitas são aplicadas estrategicamente para facilitar o movimento natural do corpo.', ARRAY['Suporte muscular e articular','Melhora da circulação','Redução de edemas','Correção postural','Alívio de dor'], ARRAY['Lesões musculares','Edema pós-cirúrgico','Instabilidade articular','Dor postural','Recuperação esportiva'], ARRAY['Alergia ao adesivo','Pele lesionada','Trombose venosa profunda','Dermatites ativas'], 'Fitas elásticas de algodão são aplicadas sobre a pele seguindo a anatomia muscular, criando ondulações que estimulam receptores cutâneos e facilitam a drenagem.', '20-40 minutos', 'Sparkles', 6),
('drenagem-linfatica', 'Drenagem Linfática', 'Detox e Redução de Inchaço', 'Técnica especializada de massagem com movimentos suaves e rítmicos que estimulam o sistema linfático, promovendo a eliminação de toxinas e redução de retenção de líquidos.', ARRAY['Redução de inchaço','Eliminação de toxinas','Melhora do sistema imunológico','Combate à celulite','Pré e pós-operatório'], ARRAY['Retenção de líquidos','Pós-operatório cirúrgico','Celulite','Gestação (a partir do 2º trimestre)','Sensação de peso nas pernas'], ARRAY['Infecções ativas','Trombose venosa profunda','Insuficiência cardíaca descompensada','Câncer ativo sem liberação médica'], 'Movimentos lentos, rítmicos e com pressão leve são aplicados seguindo o trajeto dos vasos linfáticos, direcionando o líquido para os linfonodos.', '60-90 minutos', 'Sparkles', 7),
('massagem-modeladora', 'Massagem Modeladora', 'Contorno e Firmeza', 'Técnica vigorosa que trabalha a camada adiposa e muscular para remodelar o contorno corporal. Utiliza movimentos rápidos e profundos para ativar a circulação e a lipólise.', ARRAY['Redução de medidas','Melhora do contorno corporal','Ativação da circulação','Combate à celulite e gordura localizada','Firmeza da pele'], ARRAY['Gordura localizada','Celulite graus I a III','Flacidez tissular','Pós-drenagem linfática','Preparação para eventos'], ARRAY['Varizes severas','Fragilidade capilar','Inflamações locais','Gestação'], 'Utiliza manobras de amassamento, pinçamento e deslizamento profundo com ritmo acelerado, podendo ser potencializada com ativos redutores e equipamentos.', '50-70 minutos', 'Sparkles', 8),
('aromaterapia', 'Aromaterapia', 'Cura pelos Aromas', 'Prática terapêutica que utiliza óleos essenciais puros extraídos de plantas para promover equilíbrio físico, mental e emocional. Pode ser aplicada via inalação, massagem ou banhos.', ARRAY['Redução do estresse e ansiedade','Melhora do sono','Alívio de dores','Equilíbrio emocional','Fortalecimento do sistema imunológico'], ARRAY['Estresse e ansiedade','Insônia','Dores de cabeça','Desequilíbrio emocional','Problemas respiratórios leves'], ARRAY['Alergia a óleos essenciais específicos','Gestação (óleos específicos)','Epilepsia (óleos específicos)','Crianças menores de 2 anos'], 'Óleos essenciais são selecionados de acordo com as necessidades individuais e aplicados via difusão, massagem com óleos carreadores ou inalação direta.', '60-90 minutos', 'Leaf', 9),
('reflexologia-podal', 'Reflexologia Podal', 'Equilíbrio pelos Pés', 'Técnica milenar que trabalha pontos reflexos nos pés correspondentes a órgãos e sistemas do corpo. A pressão nestes pontos estimula o equilíbrio e a autocura do organismo.', ARRAY['Equilíbrio do organismo','Alívio de dores','Melhora da circulação','Redução do estresse','Desintoxicação'], ARRAY['Estresse crônico','Desequilíbrios digestivos','Dores de cabeça frequentes','Insônia','Problemas circulatórios'], ARRAY['Fraturas nos pés','Trombose nos membros inferiores','Micoses graves','Feridas abertas nos pés'], 'O terapeuta aplica pressão em pontos específicos dos pés usando técnicas de polegar e dedo, seguindo mapas reflexológicos que conectam cada área do pé a um órgão.', '45-60 minutos', 'Sparkles', 10),
('limpeza-de-pele', 'Limpeza de Pele Tradicional', 'Revitalização Facial', 'Procedimento estético facial completo que inclui higienização, esfoliação, extração de comedões, tonificação e hidratação profunda. Essencial para manter a saúde e beleza da pele.', ARRAY['Remoção de impurezas e cravos','Desobstrução dos poros','Melhora da textura da pele','Prevenção de acne','Pele mais luminosa'], ARRAY['Pele oleosa e acneica','Cravos e comedões','Pele sem brilho','Preparação para outros tratamentos','Manutenção periódica'], ARRAY['Pele com queimadura solar','Rosácea em crise','Herpes ativo','Dermatite de contato aguda'], 'O protocolo inclui: higienização, esfoliação enzimática ou mecânica, vapor de ozônio, extração manual, alta frequência, máscara calmante e protetor solar.', '60-90 minutos', 'SmilePlus', 11),
('yugen-facespa', 'Yūgen FaceSPA', 'Ritual Facial Japonês', 'Experiência exclusiva de spa facial inspirada na filosofia japonesa do Yūgen — a beleza do mistério profundo. Combina técnicas de Kobido, Gua Sha e rituais orientais para rejuvenescer e harmonizar.', ARRAY['Rejuvenescimento facial natural','Lifting não invasivo','Harmonização facial','Relaxamento profundo','Luminosidade da pele'], ARRAY['Sinais de envelhecimento','Flacidez facial','Pele sem viço','Tensão facial e mandibular','Busca por autocuidado premium'], ARRAY['Inflamações faciais ativas','Preenchimentos recentes (menos de 15 dias)','Rosácea em crise aguda'], 'Ritual exclusivo com limpeza com águas florais, massagem Kobido (lifting japonês), Gua Sha com pedras de jade, máscaras orientais e selagem com sérum de pérola.', '75-90 minutos', 'Sparkles', 12),
('head-spa-coreano', 'Head SPA Coreano', 'Ritual Capilar K-Beauty', 'Ritual de 5 etapas inspirado nos spas capilares coreanos: análise do couro cabeludo com microcâmera, limpeza profunda, massagem craniana terapêutica, tratamentos nutritivos e aromaterapia com vapor.', ARRAY['Saúde do couro cabeludo','Fortalecimento dos fios','Relaxamento profundo','Controle de oleosidade','Hidratação intensiva'], ARRAY['Queda capilar','Couro cabeludo sensível ou oleoso','Fios danificados','Estresse e tensão craniana','Caspa e dermatite seborreica leve'], ARRAY['Feridas abertas no couro cabeludo','Alergia a produtos capilares','Infecções no couro cabeludo'], 'Protocolo de 5 etapas: 1) Análise com microcâmera, 2) Limpeza profunda com esfoliantes, 3) Massagem craniana de 20min, 4) Ampolas e máscaras nutritivas, 5) Vapor de aromaterapia.', '90-120 minutos', 'Sparkles', 13);
