-- Inserir protocolos posturais
INSERT INTO public.protocolos (nome, descricao, tipo, duracao_semanas, sessoes_por_semana, beneficios, disponivel) VALUES
('Correção de Escoliose', 'Protocolo de exercícios corretivos para desvios laterais da coluna vertebral, com foco em fortalecimento e alongamento assimétrico.', 'postural', 12, 3, 'Melhora do alinhamento lateral da coluna, fortalecimento da musculatura paravertebral, redução de dor e desconforto, melhora da simetria corporal', true),
('Correção de Hiperlordose', 'Protocolo para redução da curvatura lombar excessiva, com exercícios de fortalecimento abdominal e alongamento de flexores do quadril.', 'postural', 10, 3, 'Redução da lordose lombar, fortalecimento do core, melhora da postura em pé, alívio de dor lombar', true),
('Correção de Cifose', 'Protocolo para retificação da curvatura torácica excessiva (corcunda), com fortalecimento de extensores e abertura peitoral.', 'postural', 10, 3, 'Redução da cifose torácica, abertura do peito, melhora da respiração, fortalecimento dos extensores da coluna', true),
('Alinhamento Postural Geral', 'Protocolo completo de reeducação postural, combinando exercícios para todas as regiões com consciência corporal.', 'postural', 8, 4, 'Melhora geral da postura, consciência corporal, redução de dores crônicas, prevenção de lesões', true),
('Correção de Ombros Anteriorizados', 'Protocolo específico para anteriorização de ombros, comum em quem trabalha sentado. Foco em abertura peitoral e fortalecimento de trapézio.', 'postural', 8, 3, 'Retração dos ombros, abertura peitoral, melhora da postura sentada, alívio de tensão cervical', true);

-- Inserir exercícios corretivos posturais
INSERT INTO public.exercicios_alongamento (nome, descricao, categoria, nivel, duracao_segundos, repeticoes, instrucoes, musculos_alvo, disponivel) VALUES
-- Escoliose
('Alongamento Lateral em Pé', 'Alongamento lateral da coluna para melhorar a flexibilidade e corrigir assimetrias.', 'postural_escoliose', 'iniciante', 30, 3, '1. Fique em pé com os pés afastados na largura dos ombros\n2. Eleve o braço do lado convexo da curva acima da cabeça\n3. Incline o tronco para o lado oposto\n4. Mantenha a posição por 30 segundos\n5. Repita 3 vezes de cada lado', 'Oblíquos, Quadrado lombar, Intercostais', true),
('Prancha Lateral Modificada', 'Fortalecimento assimétrico para estabilização lateral da coluna.', 'postural_escoliose', 'intermediario', 30, 3, '1. Deite de lado com os joelhos flexionados\n2. Apoie-se no antebraço e joelhos\n3. Eleve o quadril mantendo o corpo alinhado\n4. Mantenha por 30 segundos\n5. Repita 3 vezes de cada lado (enfatize o lado mais fraco)', 'Oblíquos, Core, Glúteo médio', true),
('Rotação Segmentar em Decúbito', 'Mobilização rotacional controlada para reduzir rigidez segmentar da coluna.', 'postural_escoliose', 'iniciante', 30, 5, '1. Deite de costas com os joelhos flexionados\n2. Mantenha os ombros no chão\n3. Leve os joelhos suavemente para um lado\n4. Mantenha 30 segundos e repita do outro\n5. Faça 5 repetições para cada lado', 'Rotadores da coluna, Oblíquos', true),
-- Hiperlordose
('Inclinação Pélvica (Pelvic Tilt)', 'Exercício fundamental para aprender a controlar a posição da pelve e reduzir a lordose lombar.', 'postural_lordose', 'iniciante', 20, 10, '1. Deite de costas com joelhos flexionados\n2. Pressione a lombar contra o chão contraindo o abdômen\n3. Mantenha por 5 segundos\n4. Relaxe e repita\n5. Faça 10 repetições', 'Transverso do abdômen, Reto abdominal, Glúteos', true),
('Ponte com Retroversão Pélvica', 'Fortalecimento de glúteos com foco na retroversão pélvica para neutralizar a hiperlordose.', 'postural_lordose', 'iniciante', 30, 10, '1. Deite de costas com joelhos flexionados\n2. Faça a retroversão pélvica (pressione lombar no chão)\n3. Eleve o quadril mantendo a retroversão\n4. Segure 3 segundos no topo\n5. Desça lentamente. Repita 10x', 'Glúteo máximo, Core, Isquiotibiais', true),
('Alongamento de Flexores do Quadril', 'Alongamento do iliopsoas para reduzir a tração anterior da pelve.', 'postural_lordose', 'iniciante', 45, 3, '1. Ajoelhe-se com um joelho no chão\n2. Avance a outra perna à frente em 90°\n3. Contraia o glúteo do lado ajoelhado\n4. Empurre suavemente o quadril para frente\n5. Mantenha 45 segundos de cada lado', 'Iliopsoas, Reto femoral, Quadríceps', true),
('Dead Bug', 'Exercício avançado de estabilização do core mantendo a coluna neutra.', 'postural_lordose', 'intermediario', 30, 8, '1. Deite de costas, braços estendidos para cima\n2. Joelhos flexionados a 90° (posição de mesa)\n3. Mantenha lombar pressionada no chão\n4. Estenda braço direito + perna esquerda simultaneamente\n5. Retorne e alterne. Faça 8 de cada lado', 'Transverso do abdômen, Core profundo', true),
-- Cifose
('Anjo na Parede', 'Exercício de mobilidade e fortalecimento dos extensores torácicos e retratores escapulares.', 'postural_cifose', 'iniciante', 30, 10, '1. Fique de costas contra a parede\n2. Mantenha lombar, ombros e cabeça na parede\n3. Cotovelos flexionados a 90° contra a parede\n4. Deslize os braços para cima (como um anjo de neve)\n5. Mantenha contato com a parede. Repita 10x', 'Trapézio médio/inferior, Romboides, Serrátil anterior', true),
('Extensão Torácica com Rolo', 'Mobilização da coluna torácica usando foam roller para reduzir a cifose.', 'postural_cifose', 'intermediario', 30, 5, '1. Posicione o rolo de espuma na região torácica\n2. Apoie a cabeça nas mãos\n3. Inspire e estenda sobre o rolo\n4. Expire e retorne\n5. Mova o rolo para diferentes segmentos. 5 rep por segmento', 'Extensores da coluna torácica, Intercostais', true),
('Alongamento Peitoral na Porta', 'Alongamento do peitoral maior para permitir retração escapular adequada.', 'postural_cifose', 'iniciante', 45, 3, '1. Fique no batente de uma porta\n2. Posicione os antebraços nos batentes\n3. Cotovelos na altura dos ombros\n4. Dê um passo à frente suavemente\n5. Sinta o alongamento no peito. Mantenha 45s', 'Peitoral maior, Peitoral menor, Deltóide anterior', true),
('Retração Escapular com Elástico', 'Fortalecimento dos retratores escapulares para combater protração crônica.', 'postural_cifose', 'iniciante', 30, 12, '1. Segure um elástico à frente com braços estendidos\n2. Puxe o elástico horizontalmente abrindo os braços\n3. Aproxime as escápulas uma da outra\n4. Segure 3 segundos\n5. Retorne lentamente. Repita 12x', 'Trapézio médio, Romboides, Deltóide posterior', true),
-- Ombros anteriorizados
('Chin Tucks (Retração Cervical)', 'Exercício para corrigir a projeção anterior da cabeça, comum em quem usa computador.', 'postural_ombros', 'iniciante', 20, 10, '1. Sente-se com postura ereta\n2. Puxe o queixo para trás (como fazer papada)\n3. Mantenha os olhos nivelados\n4. Segure 5 segundos\n5. Relaxe e repita 10 vezes', 'Flexores cervicais profundos, Suboccipitais', true),
('Abertura Torácica em Y', 'Fortalecimento da musculatura posterior alta para combater anteriorização dos ombros.', 'postural_ombros', 'intermediario', 30, 10, '1. Deite de bruços\n2. Levante os braços formando um Y\n3. Polegares apontando para cima\n4. Aperte as escápulas juntas\n5. Mantenha 3 segundos. Repita 10x', 'Trapézio inferior, Serrátil anterior, Romboides', true),
-- Postural geral
('Cat-Cow (Gato-Vaca)', 'Mobilização global da coluna para melhorar flexibilidade e consciência postural.', 'postural_geral', 'iniciante', 30, 10, '1. Posição de quatro apoios\n2. GATO: Inspire, arredonde a coluna para cima\n3. Abaixe a cabeça e contraia o abdômen\n4. VACA: Expire, arqueie a coluna para baixo\n5. Levante a cabeça e o cóccix. Alterne 10x', 'Coluna inteira, Core, Eretores da coluna', true),
('Postura da Criança Estendida', 'Alongamento global da coluna com foco em descompressão e relaxamento.', 'postural_geral', 'iniciante', 60, 3, '1. Ajoelhe-se e sente nos calcanhares\n2. Estenda os braços à frente no chão\n3. Afunde o peito em direção ao chão\n4. Relaxe a lombar e respire profundamente\n5. Mantenha 60 segundos', 'Eretores da coluna, Latíssimo dorsal, Glúteos', true),
('Prancha Frontal', 'Fortalecimento isométrico do core para estabilização postural global.', 'postural_geral', 'intermediario', 30, 3, '1. Apoie-se nos antebraços e pontas dos pés\n2. Mantenha o corpo em linha reta\n3. Contraia o abdômen e glúteos\n4. Não deixe o quadril subir ou descer\n5. Mantenha 30 segundos. Repita 3x', 'Core completo, Reto abdominal, Glúteos', true);